### ISSUE TITLE
{{renderer date-between-today}} does not work when installed from Logseq 0.10.6 Marketplace

### ISSUE THREAD

**Issue by ChasManRors** [Cologler/logseq-date-between-typescript#2]
I installed the plugin today.
I grabbed all the tests dates from https://github.com/Cologler/logseq-date-between-typescript/blob/main/src/index.test.ts
```
1997-01-01 1997-1-1 1997/01/01 1997/1/1 2011/1/8 2011/12/8 2022/1/1
2022/2/10 2023/1/1 2023/1/10 2023/1/11 2023/1/13 2023/2/1 2023/2/5
2023/2/6 2023/2/7 2023/2/8 2023/2/9
```
I pasted the examples into a new page. Below page is for demonstration not the actual values pasted, reason backticks.
![Screen Shot 2024-02-10 at 1 38 45 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/4d346dcb-cd82-41d3-91fe-b0d6f9b66410)

I actually pasted blocks of the form:
```
2024/10/1 {{renderer date-between-today}}
2024/10/1 {{renderer(date-between-today)}}
2024/10/1 {{query (renderer(date-between-today))}}
2024/10/1 {{query (renderer date-between-today)}}
```

Nothing is rendered.
![Screen Shot 2024-02-10 at 2 07 45 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/70679028-f065-4665-a582-fc1928d9adcd)

I expected `In 7 months` to be rendered.

**Comment by Cologler** [comment]
Can you try the slash command like the usage described?

**Comment by ChasManRors** [comment]
> Can you try the slash command like the usage described?

Thank you for your quick response. I tried the slash command first ;)
I am a Ruby on Rails backend dev. I have no experience with ts and little with js and non with clojurescript. But I worked as a lisp programmer for several years. If you have the energy to help me get up to speed I will be able to fix some of the Logseq bugs, I expect.

**Comment by Cologler** [comment]
I am not at home now and there are no computers nearby me. I will go home  three days later. 

If you want to debug yourself, you can try this:

1. Clone repo
2. Execute `pnpm install` on your shell to install dependencies 
3. Execute `pnpm run build` to bundle the plugin
4. Enable dev mode in logseq 
5. Load the cloned repo as plugin folder (you may need to uninstall the one from the marketplace)
6. Edit something, re-bundle, and see if it works, and then try again...

**Comment by YU000jp** [comment]
From https://discuss.logseq.com/t/what-should-i-do-if-i-can-not-tell-if-the-bug-is-in-the-plugin-or-logseq/24999

@Cologler @ChasManRors 
It worked.  If I paste only `2024/10/1 {{renderer date-between-today}}` alone in one line, it works. (Logseq v0.10.6)

**Comment by ChasManRors** [comment]
**Thank you** @YU000jp  and  @Cologler

But, I tried it again with the example you provided.
![Screen Shot 2024-02-10 at 11 10 03 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/a882ecef-65dd-45c2-8a09-4792b7f77fe2)

When I hit return I still get nothing. 
![Screen Shot 2024-02-10 at 11 17 01 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/6395e9ce-2d2f-4d84-9f99-6b39125d00fa)

I was wondering if It had anything to do with themes so I used Logseq Default Light Theme

Does this imply there is something about my environment that is causing this issue, I am on an old Intel MacBook Pro? AFAIK I have not done any configurations outside of using Marketplace to add plugins. 

Can you point me to a doc that will tell me how to start over, preferably without losing my graphs. I'll have to recall how to `git push` to my github remote, but I haven't done that in a year and I seem to recall there is some hidden github redirection file used in logseq that caused me an issue in the past.

**Comment by Cologler** [comment]
@ChasManRors What is your preferred date format?

**Comment by ChasManRors** [comment]
@Cologler It's very considerate of you to ask what my preferred date format is. But thinking about the general problem I would think it's important to take the date format from the configuration file in Logseq. Such as when I use DatePicker. I  personally get dates of the form **Feb 11th, 2024**. Hence that is my preference. Looking at the date-between code that might be harder to code and not worth the/your time, so I will accommodate to your perfs.

**Comment by Cologler** [comment]
@ChasManRors I just released the v0.0.6, it should work on your preferred date format. Try `Feb 11th, 2024 {{renderer date-between-today}}`.

**Comment by ChasManRors** [comment]
@Cologler That is great for ppl who have it working! _I still don't._ :(

**BEFORE** insertion of call to date-between
![Screen Shot 2024-02-12 at 3 20 49 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/0d3b031c-258b-4ac8-97ca-2b5a0380d46c)

**AUTO COMPLETES** proper insertion of invocation
![Screen Shot 2024-02-12 at 3 23 28 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/e898339b-c8fe-40da-a0fd-aa68b4e36dc9)

**AFTER** Hitting return, hence calling your methods
![Screen Shot 2024-02-12 at 3 24 50 PM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/1e259a48-a2cd-4428-a6b5-092b9053423f)

**Comment by Cologler** [comment]
@ChasManRors open the developer console on logseq (with CTRL+SHIFT+I), search `date-between-today` for debug output messages and see what is happening.

![image](https://github.com/Cologler/logseq-date-between-typescript/assets/10906962/14c0c11e-800a-476d-9ec9-e6388df57a92)

**Comment by ChasManRors** [comment]
Thank you very much for making this nice utility and maintaining it!
0.0.6 fixed for the new format
![Screen Shot 2024-02-13 at 11 34 00 AM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/0ef177de-005b-48ee-a28d-010d2ea9e737)
But the documented format still has an error
![Screen Shot 2024-02-13 at 11 33 04 AM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/bdb4baa2-ac4b-4955-920f-2f593c3a55de)
Stack trace seen here: Note `r` is undefined in the below trace
![Screen Shot 2024-02-13 at 11 32 27 AM](https://github.com/Cologler/logseq-date-between-typescript/assets/39455/de701cd5-bbfe-4fb9-9170-7d5d9fdfb233)

**Comment by Cologler** [comment]
@ChasManRors The plugin uses your preferred date format to parse the date, so you should not use `2023/2/8`.

> But the documented format still has an error

Your stack trace shows the error comes from logseq-cuvee:

https://github.com/QWxleA/logseq-cuvee/blob/86de87f01db45bd39c5e35a82b882add94508b3e/index.ts#L195-L196
